# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a264fe2eeba4b18dd0c4d888bc280ba055cebaa87acfb729b9079f0b181a5be940fd366b49017de4ac06a108e6451a0be7fa19ef6ed9c904189a0b347479d6c

test:
  secret_key_base: 053f0c2a5cb1a4793029a8fc0e16e6bc903094f250b260f1a5f96052d406cafd39e0d61221d3e9b6639106d1c2f830cded6fb8746206723881bd4febad81dfcd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
